packages:
  - projects/**/*+web*

catalog:
  '@eslint/css': ^0.9.0
  '@eslint/js': ^9.32.0
  '@eslint/json': ^0.12.0
  '@picocss/pico': ^2.1.1
  '@tsconfig/strictest': ^2.0.5
  '@typescript-eslint/parser': ^8.38.0
  astro: ^5.11.0
  cspell: ^9.2.0
  eslint: 9.30.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-prettier: ^5.5.3
  globals: ^16.3.0
  jiti: ^2.5.1
  prettier: 3.6.2
  prettier-plugin-astro: ^0.14.1
  sass: ^1.89.2
  theme-toggles: ^4.10.1
  typedoc: ^0.28.8
  typescript: ^5.8.3
  typescript-eslint: 8.35.1
  vite: ^7.0.0
  vite-plugin-top-level-await: ^1.5.0
  vite-plugin-wasm: ^3.4.1
  vitepress: ^1.6.3
  vue: "^3.5.13"

linkWorkspacePackages: true
